//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SackOfFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurants()
        {
            this.Foods = new HashSet<Foods>();
            this.Menus = new HashSet<Menus>();
        }
    
        public int RestaurantID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.TimeSpan> StartingHour { get; set; }
        public Nullable<System.TimeSpan> FinishingHour { get; set; }
        public Nullable<byte> RestaurantStatu { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Districts Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foods> Foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menus> Menus { get; set; }
        public virtual Users Users { get; set; }
    }
}
